name: .NET

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 8.0.x
        include-prerelease: true
    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --no-restore
    - name: Test
      run: dotnet test --no-build --verbosity normal
    - name: NuGet (add source)
      run: dotnet nuget add source --username simontjell --password ${{ secrets.GITHUB_TOKEN }} --store-password-in-clear-text --name github "https://nuget.pkg.github.com/simontjell/index.json"
    - name: Git Version
      id: version
      uses: codacy/git-version@2.7.1
    - name: Git-based semantic version
      run: |
        echo ${{ steps.version.outputs.version }}
    - name: NuGet (pack)
      run: dotnet pack --configuration Release -p:PackageVersion=${{ steps.version.outputs.version }}
    - name: NuGet (push, 1)
      run: dotnet nuget push src/EvolutionaryAlgorithm/bin/Release/*.nupkg -k ${{ secrets.GITHUB_TOKEN }} -s https://nuget.pkg.github.com/simontjell/index.json
    - name: NuGet (push, 2)
      run: dotnet nuget push src/DifferentialEvolution/bin/Release/*.nupkg -k ${{ secrets.GITHUB_TOKEN }} -s https://nuget.pkg.github.com/simontjell/index.json
